name: Test Haxe 3

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install neko
      run: |
        sudo add-apt-repository ppa:haxe/snapshots -y
        sudo apt-get update
        sudo apt install neko -y
        echo neko version: $(neko -version)

    - name: Install haxe
      run: |
        wget https://github.com/HaxeFoundation/haxe/releases/download/4.0.3/haxe-4.0.3-linux64.tar.gz
        mkdir /opt/haxe
        tar -C /opt/haxe -zxvf haxe-4.0.3-linux64.tar.gz --strip 1
        chmod 777 /opt/haxe/haxe
        chmod 777 /opt/haxe/haxelib
        export PATH=$PATH:/opt/haxe
        mkdir /opt/haxelib && /opt/haxe/haxelib setup /opt/haxelib
        echo haxe version: $(/opt/haxe/haxe --version)
        echo setting haxe env vars
        echo ::add-path::/opt/haxe
        echo ::set-env name=HAXE_STD_PATH::/opt/haxe/std

    - name: Build app
      run: |
        haxe --version
        haxe js.hxml
