name: Haxe (all versions, all platforms, all targets)

on: [push, repository_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        haxe-version: [3.4.4, 4.0.3]
        hxml: [js.hxml, cpp.hxml]

    steps:
    - uses: actions/checkout@v1
    - uses: ianharrigan/GitHubActionsTest/.github/actions/haxe@master
      with:
        haxe-version: ${{ matrix.haxe-version }}

    - name: Build app (${{ matrix.hxml }}, haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      run: |
        haxelib install ${{ matrix.hxml }} --always
        haxe ${{ matrix.hxml }}

#    - name: Build app (js)
#      run: |
#        haxelib install js.hxml --always
#        haxe js.hxml

#    - name: Build app (cpp)
#      run: |
#        haxelib install cpp.hxml --always
#        haxe cpp.hxml
