name: Test Haxe 3

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/haxe

    - name: Build app
      run: |
        haxelib install js.hxml
        haxe js.hxml
