name: Test Haxe 3

on: [push]

#env:
  #PATH: $(echo "::add-path::~/haxe")
  #HAXE_STD_PATH: ~/haxe/std

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install neko
      run: |
        sudo add-apt-repository ppa:haxe/snapshots -y
        sudo apt-get update
        sudo apt install neko -y
        echo neko version:
        neko -version

    - name: Install haxe
      run: |
        wget https://github.com/HaxeFoundation/haxe/releases/download/4.0.3/haxe-4.0.3-linux64.tar.gz
        mkdir ~/haxe
        tar -C ~/haxe -zxvf haxe-4.0.3-linux64.tar.gz --strip 1
        chmod 777 ~/haxe/haxe
        chmod 777 ~/haxe/haxelib
        echo ::add-path::~/haxe
        echo ::set-env name=HAXE_STD_PATH::~/haxe/std
        export PATH=$PATH:~/haxe
        mkdir ~/haxelib && ~/haxe/haxelib setup ~/haxelib
        echo haxe version: $(~/haxe/haxe --version)

    - name: Build app
      run: |
        #export PATH=$PATH:~/haxe
        #export HAXE_STD_PATH=~/haxe/std
        haxe --version
        haxe js.hxml
