name: Haxe 4 (Windows)

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ianharrigan/GitHubActionsTest/.github/actions/haxe@master
      with:
        platform: win64
        haxe-version: 4.0.3

    - name: Build app
      run: |
        haxelib install js.hxml
        haxe js.hxml
