name: Test Haxe 3

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PATH: "$PATH:~/haxe"
      HAXE_STD_PATH: "~/haxe/std"

    steps:
    - uses: actions/checkout@v1

    - name: Install neko
      run: |
        sudo add-apt-repository ppa:haxe/snapshots -y
        sudo apt-get update
        sudo apt install neko -y
        echo neko version:
        neko -version
        pwd

    - name: Install haxe
      run: |
        wget https://github.com/HaxeFoundation/haxe/releases/download/4.0.3/haxe-4.0.3-linux64.tar.gz
        mkdir ~/haxe
        tar -C ~/haxe -zxvf haxe-4.0.3-linux64.tar.gz --strip 1
        chmod 777 ~/haxe/haxe
        chmod 777 ~/haxe/haxelib
        mkdir ~/haxelib && haxelib setup ~/haxelib
        echo haxe version:
        haxe --version

    - name: Build app
      run: |
        haxe --version
        haxe js.hxml
